### ISSUE TITLE
Get column usage information

### ISSUE THREAD

**Issue by dylanvanw** [rjh336/dbt-model-usage#7]
## What
As someone that looks at the usage of bigquery tables, it would be great to see the usage per column on a table.

## Why
Since BigQuery is a columnar database, most users will select the data they need per column. Having information about usage a per column basis would help identify which columns in a table are no longer used.

## How
I want to built a solution like this anyways so it would be great if we could collaborate on this and I could add it to this package.

These are two types of usage patterns of columns that I thought of. First, there is the non-specific 'SELECT *' that would mean the column gets queried but does not indicate that the users really wants a specific column. Second, there is the specific 'SELECT column' that indicates that the column is being used. This last one would also hold for cases where it is used in the other clauses like WHERE, ORDER BY, GROUP BY, and HAVING

**Comment by rjh336** [comment]
@dylanvanw I currently have a column specific test called `column_queried_within_last` which does a very basic scan for a column name within an executed query to check for explicit references to that column. Do you have some ideas for improving that test?

Or are you proposing something else?

**Comment by dylanvanw** [comment]
@rjh336 that does look like what I was thinking about. Thank you for pointing that out, I didn't see that before.
